name: Deploy_chatbot_api
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code 
        uses: actions/checkout@v2

      - name: Configurer python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Installer les dépendances Python
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécution des tests avec pytest
        run: |
          . venv/bin/activate
          pytest tests/
